services:
  backend:
    build: ./backend
    environment:
      - DEBUG=${DEBUG:-false}
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/database}
      - PROMPTS=${PROMPTS:-static/prompts/}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-true}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT:-https://api.smith.langchain.com}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-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}
      - SAMBANOVA_API_KEY=${SAMBANOVA_API_KEY:-e66dce4b-5f25-4714-b5ce-398eddeda808}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-TCC}

    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    links:
      - "db:database"

  frontend:
    build:
      context: ./frontend
      target: development
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL:-http://localhost:8000}"
      - CHOKIDAR_USE_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: -admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - db
    volumes:
       - pgadmin:/var/lib/pgadmin 
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db-data:
  pgadmin: