services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/database
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    links:
      - "db:database"
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: -admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - db
    volumes:
       - pgadmin:/var/lib/pgadmin 
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db-data:
  pgadmin: