FROM python:3.10 AS base

RUN apt-get update \
	&& apt-get -y install gcc \
	&& rm -rf /var/lib/apt/lists/* 

FROM base AS development
ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # Poetry's configuration:
  POETRY_NO_INTERACTION=1 \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local' \
  POETRY_VERSION=1.8.4


# Copy the requirements file
RUN pip install "poetry==${POETRY_VERSION}"
COPY poetry.lock pyproject.toml ./

# Expose the port the application will run on

FROM development AS builder
WORKDIR /app
COPY . . 

RUN poetry install
EXPOSE 8000
CMD ["poetry", "run" ,"uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]