"""data_source_script

Revision ID: 189e653ca3c1
Revises: d5bf47ace6c5
Create Date: 2025-01-10 18:24:15.137822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189e653ca3c1'
down_revision: Union[str, None] = 'd5bf47ace6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    op.add_column('data_sources', sa.Column('script', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'script')
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name='requirements_data_source_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='requirements_pkey')
    )
    # ### end Alembic commands ###
