"""add column code to requirement

Revision ID: 29962d29ac02
Revises: b1a5d8c2841f
Create Date: 2024-12-22 23:49:13.548463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29962d29ac02'
down_revision: Union[str, None] = 'b1a5d8c2841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts')
    op.add_column('requirements', sa.Column('code', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'code')
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scripts_pkey')
    )
    # ### end Alembic commands ###
