"""ADD: data_source_type as an model

Revision ID: b1a5d8c2841f
Revises: bbfd2906a0bb
Create Date: 2024-12-15 14:02:43.649657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a5d8c2841f'
down_revision: Union[str, None] = 'bbfd2906a0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data_sources', sa.Column('type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'data_sources', 'data_source_type', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('data_sources', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('type', postgresql.ENUM('CSV', 'SQL', 'XLSX', 'JSON', name='datasourcetype'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.drop_column('data_sources', 'type_id')
    op.drop_table('data_source_type')
    # ### end Alembic commands ###
