"""Task

Revision ID: c9dba7227fc3
Revises: a80d0e85b04c
Create Date: 2024-11-24 09:00:33.092070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dba7227fc3'
down_revision: Union[str, None] = 'a80d0e85b04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('requirement_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'requirements', ['requirement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'requirement_id')
    # ### end Alembic commands ###
