"""rm_requirements_title

Revision ID: d6b813c78116
Revises: 27d3f1f89002
Create Date: 2024-12-29 19:58:56.805008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b813c78116'
down_revision: Union[str, None] = '27d3f1f89002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
